project:
  type: book

book:
  title: "Applied Artificial Intelligence and Deep Learning Book"
  author:
    - name: Tim Mayer
      affiliations:
        - id: nasa-earthtrise
          name: NASA - EarthRISE
        - id: UofA-huntsville
          name: The University of Alabama in Huntsville
    - name: Biplov Bhandari
      affiliations:
        - id: woolpert
          name: Woolpert Digital Innovations
    - name: David Saah
      affiliations:
        - id: USF
          name: University of San Francisco
        - id: spatial-informatics-group
          name: Spatial Informatics Group

  date: "9/18/2025"
  cover-image: Images/Book_Cover_delta_6_25.png #images/Book_Cover.png
  # repo-url: https://servir.github.io/SERVIR-Applied-Deep-Learning-Book/ #https://mayert1.github.io/quarto_book_trial/
  repo-url: https://github.com/NASA-EarthRISE/EarthRISE-Applied-Artificial-Intelligence-and-Deep-Learning-Book
  repo-actions: [source, edit, issue]
  downloads: [pdf]
  chapters:
    - index.md
    - part: "Curriculum"
      chapters:
        - 02-Data-Preparation/index.ipynb
        - 03_Semantic_Segmentation/01__Crop_Mapping/notebooks/Rice_Mapping_Bhutan_2021.ipynb
        - 04_Object_Detection/index.ipynb
        - 05_Time_Series/index.ipynb
        - 06_Eco_Process_Sim/index.ipynb
        - 07_Transfer_Learning/index.ipynb
        - 08_Fusion/index.ipynb
        - 09_Downscaling/index.ipynb
        - 10_Future/index.ipynb
        - 11_Ethics/index.ipynb
        - 12_Conclusions/index.ipynb
    - references.qmd
bibliography: references.bib

format:
  html:
    theme:  # pandoc, default, flatly, darkly, sketchy, sandstone, cyborg, zephyr
      light: flatly
      dark: darkly
    # code-fold: true
    # code-summary: "Show code"
    # output-fold: true
    # output-summary: "Show output"
    page-tools: ["colab", "github", "source", "edit", "issue"]
  pdf:
    documentclass: scrreprt  # book
    page-tools: [] # Remove page tools for PDF
    code-fold: false  # Don't fold code in PDF
    output-fold: false  # Don't fold output in PDF
  # page-tools: ["colab", "github"]

website:
  google-analytics: "G-FSHTGR1D98"